# Directories
log_dir: "logs_metacells"
code_dir: "../../../code/train_rna"
out_dir: "../../../out/v5/metacells_rna"

# Input files
tcga_xena_path: "/data1/chanj3/LUAS.multiome.results/TCGA_expression_modeling/data/EB++AdjustPANCAN_IlluminaHiSeq_RNASeqV2.geneExp.xena"
tcga_clindata_path: "/data1/chanj3/LUAS.multiome.results/TCGA_expression_modeling/data/Survival_SupplementalTable_S1_20171025_xena_sp"
samplesheet: "metacells_samplesheet.csv"

# Conda environments
snapatac2_env: "/home/yangf4/envs/SnapATAC2"
infercnv_env: "/home/yangf4/envs/infercnv"

# Gene sets to process
gene_sets:
  - "hvg_5000"
  - "hvg_3000"
  - "hvg_1000"
  - "hvg_500"
  - "max_fdr_1e-6_min_logfc_2"
  - "max_fdr_1e-6_min_logfc_2_top_200_per"
