# Directories
log_dir: "logs_metacells"
code_dir: "../../../code/apply_models"
out_dir: "../../../out/v5/metacells"

samplesheet: "metacells_samplesheet.csv"

peak_set: "fdr_1e-6_top_2500_per"
gene_set: "max_fdr_1e-6_min_logfc_2_top_200_per"
atac_C: "0.1"
rna_C: "0.001"
rna_dir: "../../../out/v5/metacells/rna"
atac_dir: "../../../out/v5/metacells/atac"
default_C: "1"

# Conda environments
snapatac2_env: "/home/yangf4/envs/SnapATAC2"
